spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///kombined
    username: ${kombinedDbUser}
    password: ${kombinedDbPassword}
    properties: 
      socketFactory: com.google.cloud.sql.mysql.SocketFactory
      cloudSqlInstance: kombined-site:europe-west1:kombined