spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///kombined?cloudSqlInstance=kombined-site:europe-west1:kombined&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=${kombinedDbUser}&password=${kombinedDbPassword}
    username: ${kombinedDbUser}
    password: ${kombinedDbPassword}
  cloud:
    gcp:
      sql:
        database-name: kombined
        instance-connection-name: kombined-site:europe-west1:kombined
